// Autogenerated from Pigeon (v17.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DeviceInfo {
    private @Nullable String deviceName;

    public @Nullable String getDeviceName() {
      return deviceName;
    }

    public void setDeviceName(@Nullable String setterArg) {
      this.deviceName = setterArg;
    }

    private @Nullable String deviceModel;

    public @Nullable String getDeviceModel() {
      return deviceModel;
    }

    public void setDeviceModel(@Nullable String setterArg) {
      this.deviceModel = setterArg;
    }

    public static final class Builder {

      private @Nullable String deviceName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDeviceName(@Nullable String setterArg) {
        this.deviceName = setterArg;
        return this;
      }

      private @Nullable String deviceModel;

      @CanIgnoreReturnValue
      public @NonNull Builder setDeviceModel(@Nullable String setterArg) {
        this.deviceModel = setterArg;
        return this;
      }

      public @NonNull DeviceInfo build() {
        DeviceInfo pigeonReturn = new DeviceInfo();
        pigeonReturn.setDeviceName(deviceName);
        pigeonReturn.setDeviceModel(deviceModel);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(deviceName);
      toListResult.add(deviceModel);
      return toListResult;
    }

    static @NonNull DeviceInfo fromList(@NonNull ArrayList<Object> list) {
      DeviceInfo pigeonResult = new DeviceInfo();
      Object deviceName = list.get(0);
      pigeonResult.setDeviceName((String) deviceName);
      Object deviceModel = list.get(1);
      pigeonResult.setDeviceModel((String) deviceModel);
      return pigeonResult;
    }
  }

  private static class DeviceInfoApiCodec extends StandardMessageCodec {
    public static final DeviceInfoApiCodec INSTANCE = new DeviceInfoApiCodec();

    private DeviceInfoApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return DeviceInfo.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof DeviceInfo) {
        stream.write(128);
        writeValue(stream, ((DeviceInfo) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface DeviceInfoApi {

    @NonNull 
    DeviceInfo getDeviceInfo();

    /** The codec used by DeviceInfoApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return DeviceInfoApiCodec.INSTANCE;
    }
    /**Sets up an instance of `DeviceInfoApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable DeviceInfoApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.com.example.flutter_animation_practice.DeviceInfoApi.getDeviceInfo", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  DeviceInfo output = api.getDeviceInfo();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
